# Generated by Django 5.1.3 on 2024-11-14 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='dailyintake',
            name='food_eaten',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='api.food'),
        ),
        migrations.AlterField(
            model_name='dailyintake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_intakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weighttracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
