# Generated by Django 5.1.3 on 2024-11-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_food_options_alter_dailyintake_food_eaten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
