# Generated by Django 5.1.3 on 2024-11-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_food_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=100.0, max_digits=6),
        ),
    ]
