# Generated by Django 5.1.3 on 2024-11-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_food_calories_alter_food_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyintake',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dailyintake',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dailyintake',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dailyintake',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6),
        ),
    ]
