# Generated by Django 5.1.3 on 2025-01-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weighttracker',
            unique_together={('user', 'weight_entry_date')},
        ),
    ]
