# Generated by Django 5.1.3 on 2025-01-19 09:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_weighttracker_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyintake',
            name='food_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
