# Generated by Django 5.1.3 on 2025-01-28 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_weighttracker_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighttracker',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
