# Generated by Django 5.1.3 on 2025-01-30 18:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_weighttracker_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyintake',
            name='food_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=6),
        ),
    ]
