# Generated by Django 5.1.3 on 2025-02-11 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_dailyintake_food_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyintake',
            name='food_entry_date',
            field=models.DateField(default=datetime.date(2025, 2, 11)),
        ),
        migrations.AlterField(
            model_name='weighttracker',
            name='weight_entry_date',
            field=models.DateField(default=datetime.date(2025, 2, 11)),
        ),
    ]
